[debug] [2019-06-14T07:35:31.262Z] ----------------------------------------------------------------------
[debug] [2019-06-14T07:35:31.264Z] Command:       /usr/bin/node /usr/bin/firebase login --reauth
[debug] [2019-06-14T07:35:31.264Z] CLI Version:   7.0.0
[debug] [2019-06-14T07:35:31.264Z] Platform:      linux
[debug] [2019-06-14T07:35:31.264Z] Node Version:  v10.14.2
[debug] [2019-06-14T07:35:31.475Z] Time:          Fri Jun 14 2019 07:35:31 GMT+0000 (GMT)
[debug] [2019-06-14T07:35:31.475Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=962028809&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2019-06-14T07:35:41.634Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2019-06-14T07:36:02.647Z] Token Fetch Error: Error
    at new FirebaseError (/usr/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/usr/lib/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/usr/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.onRequestError (/usr/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at ClientRequest.onError (/usr/lib/node_modules/firebase-tools/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:273:13)
